/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'role' : string,
  'text' : string,
  'timestamp' : Time,
  'senderName' : string,
}
export type ClassType = { 'six' : null } |
  { 'seven' : null };
export interface Content {
  'live' : string,
  'notes' : string,
  'recorded' : Array<string>,
  'questions' : Array<Question>,
}
export type ExternalBlob = Uint8Array;
export interface Question {
  'question' : string,
  'correctAnswerIndex' : bigint,
  'options' : Array<string>,
}
export type Subject = { 'maths' : null } |
  { 'science' : null };
export interface Submission {
  'studentName' : string,
  'subject' : Subject,
  'score' : bigint,
  'classType' : ClassType,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addChatMessage' : ActorMethod<
    [ClassType, Subject, string, string, string],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatMessages' : ActorMethod<[ClassType, Subject], Array<ChatMessage>>,
  'getClassContent' : ActorMethod<[ClassType, Subject], Content>,
  'getGooglePayQrBlob' : ActorMethod<[], [] | [ExternalBlob]>,
  'getTestSubmission' : ActorMethod<
    [string, ClassType, Subject],
    [] | [Submission]
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'submitTest' : ActorMethod<[string, ClassType, Subject, bigint], undefined>,
  'updateClassContent' : ActorMethod<
    [ClassType, Subject, string, Array<string>, string, Array<Question>],
    undefined
  >,
  'updateGooglePayQrBlob' : ActorMethod<[ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];