/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ClassType = IDL.Variant({ 'six' : IDL.Null, 'seven' : IDL.Null });
export const Subject = IDL.Variant({
  'maths' : IDL.Null,
  'science' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ChatMessage = IDL.Record({
  'role' : IDL.Text,
  'text' : IDL.Text,
  'timestamp' : Time,
  'senderName' : IDL.Text,
});
export const Question = IDL.Record({
  'question' : IDL.Text,
  'correctAnswerIndex' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});
export const Content = IDL.Record({
  'live' : IDL.Text,
  'notes' : IDL.Text,
  'recorded' : IDL.Vec(IDL.Text),
  'questions' : IDL.Vec(Question),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Submission = IDL.Record({
  'studentName' : IDL.Text,
  'subject' : Subject,
  'score' : IDL.Nat,
  'classType' : ClassType,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addChatMessage' : IDL.Func(
      [ClassType, Subject, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatMessages' : IDL.Func(
      [ClassType, Subject],
      [IDL.Vec(ChatMessage)],
      ['query'],
    ),
  'getClassContent' : IDL.Func([ClassType, Subject], [Content], ['query']),
  'getGooglePayQrBlob' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
  'getTestSubmission' : IDL.Func(
      [IDL.Text, ClassType, Subject],
      [IDL.Opt(Submission)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'submitTest' : IDL.Func([IDL.Text, ClassType, Subject, IDL.Nat], [], []),
  'updateClassContent' : IDL.Func(
      [
        ClassType,
        Subject,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Vec(Question),
      ],
      [],
      [],
    ),
  'updateGooglePayQrBlob' : IDL.Func([ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ClassType = IDL.Variant({ 'six' : IDL.Null, 'seven' : IDL.Null });
  const Subject = IDL.Variant({ 'maths' : IDL.Null, 'science' : IDL.Null });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ChatMessage = IDL.Record({
    'role' : IDL.Text,
    'text' : IDL.Text,
    'timestamp' : Time,
    'senderName' : IDL.Text,
  });
  const Question = IDL.Record({
    'question' : IDL.Text,
    'correctAnswerIndex' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  const Content = IDL.Record({
    'live' : IDL.Text,
    'notes' : IDL.Text,
    'recorded' : IDL.Vec(IDL.Text),
    'questions' : IDL.Vec(Question),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Submission = IDL.Record({
    'studentName' : IDL.Text,
    'subject' : Subject,
    'score' : IDL.Nat,
    'classType' : ClassType,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addChatMessage' : IDL.Func(
        [ClassType, Subject, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatMessages' : IDL.Func(
        [ClassType, Subject],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'getClassContent' : IDL.Func([ClassType, Subject], [Content], ['query']),
    'getGooglePayQrBlob' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
    'getTestSubmission' : IDL.Func(
        [IDL.Text, ClassType, Subject],
        [IDL.Opt(Submission)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'submitTest' : IDL.Func([IDL.Text, ClassType, Subject, IDL.Nat], [], []),
    'updateClassContent' : IDL.Func(
        [
          ClassType,
          Subject,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Vec(Question),
        ],
        [],
        [],
      ),
    'updateGooglePayQrBlob' : IDL.Func([ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };